name: "build"
on: [push, pull_request]
env:
  TRIVY_VERSION: 0.30.0
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Setup Bats libs
        uses: brokenpip3/setup-bats-libs@0.1.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}

      - name: Test
        run: bats --recursive --timing .

      - name: Debug show artifacts
        if: always()
        run: |
          cat ./config.test
          cat ./fs-scheck.test